# Generated by Django 3.0.8 on 2020-08-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_donor_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='state',
            field=models.CharField(default='maryland', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='zip_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
