# Generated by Django 3.0.8 on 2020-08-11 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_response'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='user',
            new_name='patient',
        ),
    ]
