# Generated by Django 3.0.8 on 2020-08-12 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20200811_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='myapp.Patient'),
        ),
    ]
