# Generated by Django 3.0.8 on 2020-08-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20200812_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Video_Description', models.CharField(max_length=500)),
                ('videofile', models.FileField(blank=True, default='default.png', upload_to='')),
            ],
        ),
    ]
